# Generated by Django 5.2.8 on 2025-11-14 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PredictionHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prediction_date", models.DateTimeField(auto_now_add=True)),
                ("Hectares", models.FloatField()),
                ("Seedrate_in_Kg", models.FloatField()),
                ("LP_Mainfield_in_Tonnes", models.FloatField()),
                ("Nursery_area_Cents", models.FloatField()),
                ("LP_nurseryarea_in_Tonnes", models.FloatField()),
                ("DAP_20days", models.FloatField()),
                ("Weed28D_thiobencarb", models.FloatField()),
                ("Urea_40Days", models.FloatField()),
                ("Potassh_50Days", models.FloatField()),
                ("Micronutrients_70Days", models.FloatField()),
                ("Pest_60Day_in_ml", models.FloatField()),
                ("d30DRain_in_mm", models.FloatField()),
                ("d30DAI_in_mm", models.FloatField()),
                ("d30_50DRain_in_mm", models.FloatField()),
                ("d30_50DAI_in_mm", models.FloatField()),
                ("d51_70DRain_in_mm", models.FloatField()),
                ("d51_70AI_in_mm", models.FloatField()),
                ("d71_105DRain_in_mm", models.FloatField()),
                ("d71_105DAI_in_mm", models.FloatField()),
                ("Min_temp_D1_D30", models.FloatField()),
                ("Max_temp_D1_D30", models.FloatField()),
                ("Min_temp_D31_D60", models.FloatField()),
                ("Max_temp_D31_D60", models.FloatField()),
                ("Min_temp_D61_D90", models.FloatField()),
                ("Max_temp_D61_D90", models.FloatField()),
                ("Min_temp_D91_D120", models.FloatField()),
                ("Max_temp_D91_D120", models.FloatField()),
                ("Inst_Wind_Speed_D1_D30_in_Knots", models.FloatField()),
                ("Inst_Wind_Speed_D31_D60_in_Knots", models.FloatField()),
                ("Inst_Wind_Speed_D61_D90_in_Knots", models.FloatField()),
                ("Inst_Wind_Speed_D91_D120_in_Knots", models.FloatField()),
                ("Relative_Humidity_D1_D30", models.FloatField()),
                ("Relative_Humidity_D31_D60", models.FloatField()),
                ("Relative_Humidity_D61_D90", models.FloatField()),
                ("Relative_Humidity_D91_D120", models.FloatField()),
                ("Trash_in_bundles", models.FloatField()),
                ("Agriblock_encoded", models.FloatField(default=0.0)),
                ("Variety_encoded", models.FloatField(default=0.0)),
                ("Soil_Type_encoded", models.FloatField(default=0.0)),
                ("Wind_Direction_D1_D30_encoded", models.FloatField(default=0.0)),
                ("predicted_yield_kg", models.FloatField(blank=True, null=True)),
                (
                    "recommended_variety",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predictions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
